# Generated by Django 5.1.1 on 2024-10-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='license',
            name='license_key',
        ),
        migrations.AddField(
            model_name='license',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
